"""
ComfyUI-ICLoRA-Anima
IC-LoRA + OminiControl + Multi-Frame generation for Anima model.
"""

from .nodes import NODE_CLASS_MAPPINGS as IC_LORA_NODES, NODE_DISPLAY_NAME_MAPPINGS as IC_LORA_NAMES
from .multiframe import NODE_CLASS_MAPPINGS as MF_NODES, NODE_DISPLAY_NAME_MAPPINGS as MF_NAMES
from .ominicontrol import NODE_CLASS_MAPPINGS as OC_NODES, NODE_DISPLAY_NAME_MAPPINGS as OC_NAMES

NODE_CLASS_MAPPINGS = {**IC_LORA_NODES, **MF_NODES, **OC_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**IC_LORA_NAMES, **MF_NAMES, **OC_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
